export const CONSTANTS = {
  GRID_SIZE: 20,
  VOXEL_SIZE: 1,
  CAMERA: {
    FRUSTUM_SIZE: 20,
    NEAR: 0.1,
    FAR: 1000,
    INITIAL_POSITION: { x: 20, y: 20, z: 20 }
  },
  ANIMATION: {
    ROTATION_DURATION: 0.5
  },
  PHYSICS: {
    GRAVITY: 30,
    JUMP_FORCE: 12,
    MOVE_SPEED: 10,
    TERMINAL_VELOCITY: 20
  },
  OCCLUSION: {
    RAY_TOLERANCE: 0.2,
    FADE_OPACITY: 0.2
  },
  COLORS: {
    OCCLUSION_HIGHLIGHT: 0x555555,
    DEFAULT_EMISSIVE: 0x000000
  }
};
